name: Golang Application
on:
  push:
    branches:
      - 'v1.0'
    tags:
      - 'latest'
jobs:
  ci:
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
